### ISSUE TITLE
Randomized enemies

### ISSUE THREAD

**Issue by jayman9696** [TheWreckingCrewUK/Insurgency-Redux-Legacy#15]
Randomised enemy counts per patrol, and random weapons per unit (weighted chances) - not necessarily russian equipment

**Comment by Bosenator** [comment]
Should be scalable to a reasonable degree on current player count, too.

**Comment by CrowJM64** [comment]
Would there also be more randomised outfits, as it gets to the point where you see a black outfit and you know he has an RPG.

**Comment by jayman9696** [comment]
Hostiles spawn dynamically based on playercount and moral as of 8fb111e. As for different types of enemies that is moved to 1.1
