### ISSUE TITLE
civililians medical patch up reward

### ISSUE THREAD

**Issue by jayman9696** [TheWreckingCrewUK/Insurgency-Redux-Legacy#17]
possibly make their way to the base

**Comment by Bosenator** [comment]
Possibly hook into advanced medical, give a point based reward on successful treatment. 

Perhaps has a random chance of spawning a new objective as well, that's tangible linked - like a cache/IED factory general location marker, a tip off on a possible attack etc.

**Comment by Frozeph** [comment]
would this count as a side mission?

**Comment by Bosenator** [comment]
There will be no side missions. All objectives will contribute to overall victory in the area, and failure will negatively contribute as well.

**Comment by Frozeph** [comment]
what i meant was categorised as a side mission as you have with the others sorry should have said "Objective ideas"

**Comment by Bosenator** [comment]
I don't think so - I think this will just occur when a civilian is injured (50/50 chance of them seeking help). It's then up to the players to either tackle with this problem, or to ignore it. If a civilian dies, it should negatively affect the mission, regardless of how. Probably affect the civilian morale. If a player was the reason, then perhaps we can also boost the insurgent morale.
