### ISSUE TITLE
More Civilian Vehicles & VBIEDs

### ISSUE THREAD

**Issue by jayman9696** [TheWreckingCrewUK/Insurgency-Redux-Legacy#19]
With possible ieds?

**Comment by Bosenator** [comment]
I'll ask Saxon how he did the VBIEDs for the IRA op. Something to that effect visually will suffice, with varying levels of triggers thanks to ACE explosives.

**Comment by Frozeph** [comment]
is it possible for a visual give away if the vehicle is not occupied otherwise it will result is just avoiding all civ cars for fear of big boom. Thinking if the IED could be under it, and then at least you can do a visual check

**Comment by Bosenator** [comment]
On the IRA op you could visually note the VBIEDs presence. There was "rubble" in the back of the vehicle. This is the part I will ask Saxon about.

**Comment by Frozeph** [comment]
so they rode low in the back end? thats awesome, i wonder if you can do that for them stationary so the back looks weighed down. Could even do a mixture of visual indicators for 1.1

**Comment by jayman9696** [comment]
Our normal Civilians were added in 45cdb38

Pushing to 1.1 for VBIEDS and such
