### ISSUE TITLE
Diary Guide to the mission

### ISSUE THREAD

**Issue by jayman9696** [TheWreckingCrewUK/Insurgency-Redux-Legacy#23]
Since we have many features we should create diary records under something like "how to play"

That show people how each feature works such as the forward base.

**Comment by Bosenator** [comment]
Once we've got some of the subsystems written out, and tested - i.e. in a state we're content with, then this would be a great task for one of the guys involved in the feedback as it only requires knowledge in English.

**Comment by Frozeph** [comment]
I'm happy to take this if you wanna assign me it

**Comment by jayman9696** [comment]
The basic framework was added in e335b95

As things are added simply keep this up to date with createDiaryRecord.
