### ISSUE TITLE
Point Based Victory System

### ISSUE THREAD

**Issue by jayman9696** [TheWreckingCrewUK/Insurgency-Redux-Legacy#24]
The main goal is to re-work the victory system as a point system where if you complete enough good actions and not many bad actions you win the game. 

Preferably some way to track your progress as well.

**Comment by Bosenator** [comment]
There will probably be some sort of internal point threshold, and positive actions contribute the team goal towards this, where as negative detract at varying rates. I'm thinking using 1000 points as the scale gives us enough granularity to give reasonable rewards to certain actions in relation to each other.

For example clearing an IED could contribute 2 points, killing the IED counter-attack could contribute 2 points, being killed by an IED could detract 1 point (multiple casualties would stack up) and destroying a cache contributes 30 points. 

This threshold should be able to scale upwards with the turnout. Having it scale downwards would be troublesome, could potential eclipse the current earned points and win, by having someone disconnect. I think for the moment the scaling down should just not happen, and if it becomes troublesome in the future, it's something we'll tackle then.

The tracking system for this should be entirely event handler based. This system will monitor for new point adjustments, and do the appropriate actions. This way if we add new objectives in the future, we simply need to fire the event at the appropriate time, with a point value we're happy with. Should be very pain-free to do so.
