### ISSUE TITLE
Uniform Pictures\new ones for patrol base stuff

### ISSUE THREAD

**Issue by jayman9696** [TheWreckingCrewUK/Insurgency-Redux-Legacy#25]
**Images needed:**

- [x] Radio Channels
- [x] Patrol Base Items (and construction) Help
- [x] Spawn System Help
- [x] General Main Base Posters (i.e. This is the Ammo Box)
- [x] Group Advertisement Images (and TeamSpeak)
- [x] Detention Facility Help
- [x] Loading Image

**Comment by Bosenator** [comment]
Images needed:

- Radio Channels
- Patrol Base Items (and construction) Help
- Spawn System Help
- General Main Base Posters (i.e. This is the Ammo Box)
- Group Advertisement Images (and TeamSpeak)

**Comment by Bosenator** [comment]
@jayman9696 what information do I need to display for the second and third item of the list?
