### ISSUE TITLE
VBIED Affect Suspension

### ISSUE THREAD

**Issue by Bosenator** [TheWreckingCrewUK/Insurgency-Redux-Legacy#27]
As mentioned by Fro, in #19.

> i wonder if you can do that for them stationary so the back looks weighed down. Could even do a mixture of visual indicators for 1.1

**Comment by CrowJM64** [comment]
But surely IEDs wouldn't weigh that much unless they were larger ones? (No knowledge of the weight of IEDs)

**Comment by jayman9696** [comment]
I'm just going to close this as it is borderline to  completely impossible. It would require us to make vehicles with adjusted suspension which is beyond our ability
