### ISSUE TITLE
Retrievable IEDs

### ISSUE THREAD

**Issue by Bosenator** [TheWreckingCrewUK/Insurgency-Redux-Legacy#29]
As part of an ongoing effort to remove resources from insurgent hands, IEDs that have been defused and successfully brought back to base should earn points per IED. Maybe like 2, or so.

**Comment by Bosenator** [comment]
Just occurred to me @jayman9696 - if you die after picking one up, will you have it when you respawn?

**Comment by jayman9696** [comment]
Fixed in 9be93db
