### ISSUE TITLE
Adding a patrol base

### ISSUE THREAD

**Issue by jayman9696** [TheWreckingCrewUK/Insurgency-Redux-Legacy#3]
A patrol base allowing respawns that has limited ammo and can be attacked

**Comment by Bosenator** [comment]
**Items that are required to constitute a functioning patrol base**:
- Radio (perhaps when it's placed a text input pops up prompting to give the patrol base a name)
- Generator (required to power said radio, and other patrol base functions)
- Medical Facility (tent probably)

Once all three are present within a certain radius, the patrol base is created and its associative spawn point.

**Items that are additional, that have added benefit**:
- Radar (an early warning system to give notice (pops an objective) on incoming patrol base attacks)
- Fortifications (sand bags, trenching tools, concertina wire)
- Ammo Box (a transportable "base" box, used to give a finite resupply to those spawning there, and give helicopter pilots a job still)
- Map board (users can copy their map to this object, and from it - this will coincide with the removal of global markers from users)
- Lights (some sort of ability to illuminate inwards/outwards for night time - i.e. portable lights)

**Comment by Bosenator** [comment]
Don't forget the following relate to this also: 

#22 
#18 
#10
