### ISSUE TITLE
Better morale feedback

### ISSUE THREAD

**Issue by Hobbnob** [TheWreckingCrewUK/Insurgency-Redux-Legacy#30]
Instead of morale status being readable from anywhere via the self interact ace menu, incorporate contextual morale indication into civilian textual interaction. For example, interrogating a civilian while morale is high could go something like this:

"I heard you are doing good work here, I appreciate that. I think I found an IED around this area, please be careful"

Whereas an interrogation while morale is low might go something like:

"I will not tell you anything, get away from here! You are not welcome here and you never will be, leave at once"

**Comment by Hobbnob** [comment]
Looking through our current code I noticed we already have this, but it's not very clear that the responses we get are as a result of morale and not just random. I'm currently updating what we've got with slightly more obvious responses.

**Comment by jayman9696** [comment]
I see that this was done here: https://github.com/TheWreckingCrewUK/Insurgency/commit/093e229c3203ef8ecd796dc5bb370ce30e34a186

So I am going to close it
