### ISSUE TITLE
Relocate to Server\Init

### ISSUE THREAD

**Issue by Bosenator** [TheWreckingCrewUK/Insurgency-Redux-Legacy#33]
https://github.com/TheWreckingCrewUK/Insurgency/blob/51f85cbb03fb55031d67ff1bb8fed93897022220/Insurgency_Malden.Malden/initServer.sqf#L9

Would it be possible to centralise these within Insurgency_Core\Server ?

**Comment by jayman9696** [comment]
Yes, but the real answer is to fix the twc_cache module as it isn't working and why I added it to the initServer

**Comment by Bosenator** [comment]
Can replace with #include for the moment?

**Comment by jayman9696** [comment]
Yes, but there really is no point. I'm going to close this as it really makes no difference then we can re-open this as a bug in 1.1 if the cache module never gets fixed.
