### ISSUE TITLE
Additional Civilian Morale Modifiers

### ISSUE THREAD

**Issue by Bosenator** [TheWreckingCrewUK/Insurgency-Redux-Legacy#39]
- [x] - Port @Hobbnob new Civilian Morale Modifier, which lowers Civilian morale when killed by a player (change to player check, not side for better portability).
- [x] - Add a MissionEventHandler for destruction of buildings, which will negatively affect Civilian Morale (check isRuin parameter for rigidity).

**Comment by CrowJM64** [comment]
Would it be able to differentiate between more valuable building, such as Mosques or Fuel Stations?

**Comment by Bosenator** [comment]
Yes, sort of. Not nicely.
