### ISSUE TITLE
[Malden] Create Squad Layout

### ISSUE THREAD

**Issue by Bosenator** [TheWreckingCrewUK/Insurgency-Redux-Legacy#40]
The mission.sqm for Malden is in need of playable units (or at least planned out). Once these are completed, I can create the radio banner required for #25.

**Comment by jayman9696** [comment]
same as old public,
Alpha, Bravo, Charlie, wildcat pilot, black hawk pilot.
No Attachments for now

**Comment by CrowJM64** [comment]
Depending on what this consists of, I MAY be able to help

**Comment by jayman9696** [comment]
Closed Here https://github.com/jayman9696/TheWreckingCrewUK/issues/29
