### ISSUE TITLE
[Civ] Random Patrols & Walking to Safety

### ISSUE THREAD

**Issue by Bosenator** [TheWreckingCrewUK/Insurgency-Redux-Legacy#41]
~It would be nice if there's a chance that some of them after spawning go for a bit of a walk, of course interruptible by fire etc. when they have finished bricking it, there's a bit of a chance they go for a walk again.~
- [x] Walk back when it's safe - they don't have suitable footwear for all this running.

**Comment by jayman9696** [comment]
Civs walking around would still be hard to question. Maybe ok at a walk though?

**Comment by jayman9696** [comment]
Ok, so the only "reasonable way would be to have a group or two separate from the main town group have some way points. Although we have the original issue of civilians running forever away so this wouldn't work.

The "un-reasonable" way would be to create waypoints, but the use doMove to get there. Have each waypoint "completion code" be to domove to the next one and repeat. This unfortunately, would need single group civilians and I am not sure the efficiency of that code. I would guess that way point completion is just a trigger which seems like an unnecessary loop to add.

civ patrols probably won't happen for a bit

**Comment by Bosenator** [comment]
Given the nature and complexity versus reward, I'm going to drop it from any milestone. It's something that someone can address in the future, but I think practically everything else takes precedence.
