### ISSUE TITLE
[Refactor] Insurgency_Core/server/sys_vehicleRespawn/vehicleRespawn.sqf

### ISSUE THREAD

**Issue by Bosenator** [TheWreckingCrewUK/Insurgency-Redux-Legacy#44]
Needs re-factoring at some point, not a major concern but an avenue to gain performance and adaptability in the future.

Potential efforts:
- [x] fall back on global variables for re-spawn time/distance etc. so it can be easier to adapt on a map by map basis
- [x] scheduled -> unscheduled w/ EH (destroyed, mounted, dismounted)
- [x] hook into a future debug system

**Comment by jayman9696** [comment]
Not really sure we need a "debug" for it. It is pretty simple, but the first two have been accomplished with:
d9f1b1b

**Comment by Bosenator** [comment]
Debug is a long term thing that I want to make, that displays a load of markers etc. when enabled and can be transferred to other mission types - as well as utilising the rpt but like, goal to do that was post 1.1

**Comment by jayman9696** [comment]
"displays a load of markers etc"

so something like zeus? It just seems unnecessary
