### ISSUE TITLE
Unit Display Names

### ISSUE THREAD

**Issue by jayman9696** [TheWreckingCrewUK/Insurgency-Redux-Legacy#45]
In the config we have to make the displayname less like:

> "SquadLeader (Modern)"

 and more like:

> Alpha Section Commander

**Comment by CrowJM64** [comment]
Made the changed config in your Issues Section. https://github.com/jayman9696/TheWreckingCrewUK/issues/31

**Comment by jayman9696** [comment]
This was done it in one of the twc_config public updates
