### ISSUE TITLE
TWC_fnc_spawnIED

### ISSUE THREAD

**Issue by jayman9696** [TheWreckingCrewUK/Insurgency-Redux-Legacy#51]
We have an issue with with the ied Functions. They use the same name as @twc_framework. 

Personally, I would see about removal/replacement of the @twc_framework function.

I edited the prefix from TWC to INS, but it probably isn't the best solution.

**Comment by Bosenator** [comment]
Perhaps change the framework one to a more generic twc_fnc_plantExplosive? So it's more applicable to symmetrical too?

**Comment by jayman9696** [comment]
Removed from @twc_framework
