### ISSUE TITLE
[Respawn] Sanity Checks

### ISSUE THREAD

**Issue by Bosenator** [TheWreckingCrewUK/Insurgency-Redux-Legacy#54]
We need some basic sanity checks upon respawn to prevent common issues arising, some of them are already done.

- [x] Confiscate certain weapons and equipment - all of the enemies too, because they're at base now
- [x] Check if the players side isn't what it should be - "common" issue of players being civilian upon respawn
- [x] Check if the medic is actually a medic, and if they aren't, sort it out

More to be added in the future.

**Comment by jayman9696** [comment]
for the second one. I have never seen that before and have no idea how we could do anything about it

**Comment by jayman9696** [comment]
The last one also isn't needed as we are phasing out medics with the operation medical system. We will just let any player use a FAK at base in the tent

**Comment by Bosenator** [comment]
You'll still need a section level medic, in order to give salines or use the defibs etc.
