### ISSUE TITLE
[Cache] One Man Unconscious Triggers Despawn

### ISSUE THREAD

**Issue by Bosenator** [TheWreckingCrewUK/Insurgency-Redux-Legacy#55]
As the title states, if there's one person within the cache radius, and he goes unconscious (and thus civilian) it triggers the despawn. Once he wakes up, they'll respawn.

Perhaps the condition on the despawn/spawn needs to take into account players in a disabled state, be that surrendered/captured/unconscious.

**Comment by jayman9696** [comment]
Closed as this isn't actually a bug with the current system.
