### ISSUE TITLE
PlayerList

### ISSUE THREAD

**Issue by jayman9696** [TheWreckingCrewUK/Insurgency-Redux-Legacy#58]
We need a player list so we know what slot people are in and what is available in game

Possible to make it "dynamic" with the group configs and stuff

**Comment by Bosenator** [comment]
Awaiting CBA response: https://github.com/CBATeam/CBA_A3/issues/

If they say it's a no-do, we can implement similar functionality ourselves in @twc_framework but it'd be nice if we didn't have to.

**Comment by Bosenator** [comment]
Unobtainable dynamically, not worth it hard coded.
