### ISSUE TITLE
Better Spawning™

### ISSUE THREAD

**Issue by Bosenator** [TheWreckingCrewUK/Insurgency-Redux-Legacy#59]
If the current server player count is more than one, then check if the group(s) triggering the respawn is more than one. This should mean that helicopters flying back from a drop off shouldn't trigger spawns, or en-route to pick-up shouldn't either - same for sole drivers. Also works as a reason for why individuals shouldn't lone-wolf.

**Comment by jayman9696** [comment]
Helicopters over 25M above the ground don't spawn enemies so this shouldn't be an issue. If it is we can editing the condition of the triggers
