### ISSUE TITLE
[Side Mission] Convoy Loss 

### ISSUE THREAD

**Issue by CrowJM64** [TheWreckingCrewUK/Insurgency-Redux-Legacy#6]
A convoy was supposed to be travelling from X to Y, they have not arrived and now the players must find out what the issue is. Players arrive at a scene where the convoy is ambushed and when they get within X meters, the attack recommences and the Players come under attack from 2-3 sections of infantry. Maybe Truck must be taken to the Destination in order to complete the task, and if the truck is destroyed the task fails.
Looks like this: http://imgur.com/a/dzJHe

Addition: Possible Technical presence as they destroyed a convoy 1~2?

**Comment by Bosenator** [comment]
I'm going to assign this one as 1.1, because I think it would provide a good basis to write/record a tutorial on how to make custom objectives.
