### ISSUE TITLE
[Bug] Can Drive Medical Truck Away

### ISSUE THREAD

**Issue by Bosenator** [TheWreckingCrewUK/Insurgency-Redux-Legacy#62]
Can drive the medical truck away from a functional patrol base, and it remains functional.

**Comment by jayman9696** [comment]
Are you sure, because they current way sets the fuel to 0. And when i checked it worked. However, players could refuel it.

The only other way to truly stop it while still letting people get in and heal is blow the tires out. which is less then ideal

**Comment by jayman9696** [comment]
This is it setting fuel to 0
https://github.com/jayman9696/TheWreckingCrewUK/blob/master/%40twc_config_public/addons/twc_objects/functions/fn_setUpForwardBase.sqf#L27

**Comment by Bosenator** [comment]
Tooit reported this to me as of yesterday. Uncertain if he refuelled it, but doubtful.

**Comment by Hobbnob** [comment]
I believe the fuel code is working at least in some form, as I landed a wildcat there a couple of days back to look around and came back to find it empty of fuel with no one claiming to have emptied it.
