### ISSUE TITLE
[Side Mission] Warlord VIP

### ISSUE THREAD

**Issue by CrowJM64** [TheWreckingCrewUK/Insurgency-Redux-Legacy#7]
I know this is already thought about but I thought I might as well make it an actual post.
Possibly markers like the Cache system, but in Khaki or an unused colour.
Capturing the Warlord delivers a large blow to the enemy's morale, and killing him does impact their morale but much less so that it is rewarding to Capture the Warlord.
There would be a lot of resistance, e.g. 1 Platoon~, 2 Technicals, 1 BTR-40?(The one that is an APC with an MG on the top).

Scene like this: http://imgur.com/a/ZgBZh

**Comment by Bosenator** [comment]
I'm going to assign this to 1.1, largely because there's an idea I have floating around expanding significantly pre-compositions, that are zeus compat too, and I think this would be a good use case for them.
