### ISSUE TITLE
Remove role restriction

### ISSUE THREAD

**Issue by Frozeph** [TheWreckingCrewUK/Insurgency-Redux-Legacy#76]
https://github.com/TheWreckingCrewUK/Insurgency/blob/ced670654ed98e2195eae3ce18bc3692bf7a1fa3/Insurgency_Core/client/sys_restrict/rolerestrictions.sqf#L121

**Comment by Hobbnob** [comment]
Invalid issue, blacklist was created after several months of no alternative being available due to threats and blocking. Do not bring your politics and manipulation to github again, this is not a place for childish drama
