### ISSUE TITLE
[Side Mission] Bomb Situation

### ISSUE THREAD

**Issue by CrowJM64** [TheWreckingCrewUK/Insurgency-Redux-Legacy#8]
There is a limited amount of time to save X hostages and prevent a bomb from exploding, (Possible harder explosive defusing module for this bomb), no enemies, but needs to extract the 3 hostages and defuse the bomb before it explodes and destroys the building of importance such as a mosque or hospital.
If successfully defused civilian trust jumps up immensely, if failed with civilians NOT saved, trust drops immensely, if civilians saved, that reduces the loss.

Scene similar to: http://imgur.com/a/vxPb9

**Comment by Bosenator** [comment]
We need to look into a system to make extracting hostages and non-other threats less than silly. This would be great for the framework, as missions suffer from the same problem. 

Perhaps a series of actions to tell the person to do something. Such as "Follow Me", "Get In Vehicle", "Get Out", might offer enough control without the need to arrest them?
